# Infrastructure parameters
project_id: peskas
service_account:
  name: penang-catch
  description: Penang catch data pipeline domain
  display_name: Penang catch domain
secret:
  file: ~/key.json
  name: penang-catch
validation:
  source: storage
  bucket: penang
  auth_file: "auth/gcs_auth_file.json"



source_agent: manual
data_format: csv
name: penang_catch
ingestion:
  type: all-data
