# Infrastructure parameters
project:
  id: peskas
service_account:
  name: penang-catch
  description: Penang catch data pipeline domain
  display_name: Penang catch domain
  role:
    storage:
      name: roles/storage.objectAdmin
      condition:
        expression: resource.name=="projects/_/buckets/bucket-name"
        title: resource_name_is_penang_catch_bucket
        description: Only grant access to penang-catch bucket
secret:
  file: auth/key.json
  name: penang-catch
storage:
  bucket:
    name: penang-catch
    location: ASIA
    uniform_access: on
    class: Standard
validation:
  config: cloudbuild.yaml
  api:
    image:
      name: penang-catch-validation
    service:
      name: penang-catch-validation
      region: asia-east1
  pubsub:
    topic:
      name: penang-catch-validation
    notification:
      format: json
      event: OBJECT_FINALIZE
    subscription:
      name: penang-catch-validation
      acknowledgement:
        deadline: 600
      retry:
        delay:
          min: 60s
          max: 600s
  endpoint: penang-catch-validation
  raw:
    object:
      name: penang-fisheries-landings.xlsx

