# Infrastructure parameters
project:
  id: peskas
service_account:
  name: penang-catch
  description: Penang catch data pipeline domain
  display_name: Penang catch domain
secret:
  file: auth/key.json
  name: penang-catch
storage:
  bucket:
    name: penang-catch
    location: ASIA
    uniform_access: on
    class: Standard
validation:
  api:
    image_name: penang-catch
  pubsub:
    topic:
      name: penang-catch-validation
    notification:
      format: json
      event: OBJECT_FINALIZE

data:
  raw:
    object:
      name: penang-fisheries-landings.xlsx

