# Infrastructure parameters
project:
  id: peskas
service_account:
  name: penang-catch
  description: Penang catch data pipeline domain
  display_name: Penang catch domain
secret:
  file: auth/key.json
  name: penang-catch
storage:
  bucket:
    name: penang-catch
    location: ASIA
    uniform_access: on
    class: Standard
validation:
  source: storage
  bucket: penang
  pubsub:
    topic:
      name: penang-catch-validation
      format: json
      event: OBJECT_FINALIZE



source_agent: manual
data_format: csv
name: penang_catch
ingestion:
  type: all-data
